server {
    listen 8080;
    server_name localhost;

    location / {
        proxy_pass http://fastcgi_server:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /status {
        proxy_pass http://fastcgi_server:80/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

